#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Taiki Akiyama
# SPDX-License-Identifier: BSD-3-Clause

import sys

try:
    line = input()
    n = int(line)
except ValueError:
    print("対応していません", file=sys.stderr)
    sys.exit(1)

if n < 0 or n == 0:
    print("1以上の整数にしてください", file=sys.stderr)
    sys.exit(1)

x = 0

for i in range(1, n + 1):
    x3 = (i % 3 == 0)
    i3 = ('3' in str(i))

    if x3 or i3:
        print(i)

