#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Taiki Akiyama
# SPDX-License-Identifier: BSD-3-Clause

import sys

line = input()
n = int(line)

x = 0

for i in range(1, n + 1):
    x3 = (i % 3 == 0)
    i3 = ('3' in str(i))

    if x3 or i3:
        print(i)

